### ISSUE TITLE
Can we have two different coercions to functions?

### ISSUE THREAD

**Issue by Xitian9** [semorrison/proof#11]
I think I've fixed the problem of defining the toMorphisms coercion, but the elaborator can't seem to resolve which function coercion to use where. Is this because has_coe_to_fun has the typeclass field F not as a parameter, and so it can't be used in typeclass resolution?

**Comment by kim-em** [comment]
Stephen asked about this on lean-user: <https://groups.google.com/d/msg/lean-user/VrkcyKxrXps/hnt5IqMDEAAJ>.

**Comment by Xitian9** [comment]
And it looks like the answer is: not yet, but maybe in the future.
